### ISSUE TITLE
Sample2

### ISSUE THREAD

**Issue by Veget-ables** [Veget-ables/android-app-2022#3]
```yaml
start_date: 2022/11/10
due_date: 2022/12/8
progress: 0.1
parent: 0
```
